### PR TITLE
class: add video device

### PR DESCRIPTION
**Pull request by leeebo**
UVC Device works well on ESP32S2/S3 now, please consider adding the source file.

We have tested isochronous and bulk mode, both works well.

### CODE REVIEW

**Comment by leeebo** [comment]
Hi @tore-espressif PTAL! For the version format, can we use a form like `0.15.0~n` ? `n` means the esp patch version number, to avoid the conflict with the TinyUSB version number.

**Comment by tore-espressif** [comment]
Hi @leeebo 

> an we use a form like 0.15.0~n

yes, this might be better. Version 0.15.1 was released only recently, do you think we should rename it (delete and reuplod) to v0.15.0~1 for consistency?

**Comment by leeebo** [comment]
@tore-espressif We'd better rename it, because `v0.15.1` > `v0.15.0~n`. This may break on some projects... but seems no project is affected now in [Github (search results)](https://github.com/search?q=path%3A**%2Fidf_component.yml+tinyusb&type=code).

**Comment by tore-espressif** [comment]
Uploaded in v0.15.0~2 https://components.espressif.com/components/espressif/tinyusb

**Pull request merged**
