### PR TITLE
TinyUSB release/0.15: DCD DWC2 interrupt handling cleanup

### PR DESCRIPTION
**Pull request by roma-jam**
**TinyUSB v0.15.0~5**

**Changes**
- Added ESP32P4 to README.rst
- Fixed register name in SOF interrupt handling. SOF is not a flag of the GOTGINT but the flag of GINTSTS (Bit 3).
- Fixed register name during Rx FIFO interrupt handling. RxFLvl is a flag of GINTSTS (Bit 4).
- Renamed IRQ sources for ESP32P4 target

### CODE REVIEW

**Comment by tore-espressif** [comment]
@roma-jam the changes LGTM. What else must be done before we can merge?

We will need this PR for upcoming changes in esp-idf. tinyusb version 0.15.0~4 will be yanked

**Comment by roma-jam** [comment]
@tore-espressif Nothing from my side (at least for now). 
Probably, I also want to know how to "yank" the previous version (just in case have the knowledge how to do that). 
Otherwise, feel free to merge if you agree with changes.

**Review by tore-espressif — APPROVED** [review]
LGTM!

**Comment by roma-jam** [comment]
@tore-espressif thanks, but I don’t have a permission to merge. 
Feel free to merge.

**Pull request merged**
