### PR TITLE
feat(uvc): support format frame based

### PR DESCRIPTION
**Pull request by lijunru-hub**
**Describe the PR**
Add UVC class support frame-based.

link https://github.com/hathach/tinyusb/pull/2656

### CODE REVIEW

**Comment by lijunru-hub** [comment]
@tore-espressif  PTAL

**Review by tore-espressif — APPROVED** [review]
LGTM!

**Comment by lijunru-hub** [comment]
@tore-espressif Could you please integrate this feature as soon as possible and release a new version of TinyUSB?

**Comment by tore-espressif** [comment]
@lijunru-hub here it is https://components.espressif.com/components/espressif/tinyusb/versions/0.15.0~10 :)

**Pull request merged**
