### PR TITLE
feature(uvc): Applied proprietary changes in UVC Device class

### PR DESCRIPTION
**Pull request by roma-jam**
## Requirements
- Fixed uninitialized values during streaming negotiation parameters
- Added `VIDEO_CS_ITF_VS_FORMAT_FRAME_BASED` support

## Limitations
N/A

## Breaking change
_No breaking changes_

## Testing:
 - After applying changes the `esp-video-components/esp_video/examples/uvc` could be built successfully: 
 
image

image

*NOTE: Modified component `usb_device_uvc` was used to enable possibility to use `espressif/tinyusb` component by local path. 

## Checklist

- [x] Pull Request name has appropriate format (for example: "fix(dcd_dwc2): Resolved address selection when several phy are present")
- [ ] _Optional:_ README.md updated
- [x] CI passing

## Related issues
- Changes applied also in synchronization commit:  https://github.com/espressif/tinyusb/pull/43
- Resolves fix: https://github.com/espressif/esp-video-components/commit/6e61b6fa10cdce9efe317bb4dd3e83f20ce58133#diff-f742676e9225ab4ba99adff463cfe58296bb400490cc0e4f5c635567e6be634d
- Upstream PR: https://github.com/hathach/tinyusb/pull/2656

### CODE REVIEW

**Comment by tore-espressif** [comment]
Can be closed in stead of https://github.com/hathach/tinyusb/pull/2656 ?

**Comment by tore-espressif** [comment]
@roma-jam Can we merge hathach/master to our espressif/release/v0.17 first? And then proceed with this PR?

If possible, we want to stay as close to upstream as possible, so it is not complicated to upgrade (like when we upgraded from 0.15 to 0.17)

**Comment by roma-jam** [comment]
Sure, we can. 
I have created upstream synchronization PR for release/v0.17: https://github.com/espressif/tinyusb/pull/43

We can merge it and then return back to the current PR (but in the end only the variables initialization will left in here).

**Comment by roma-jam** [comment]
The upstream synchronization https://github.com/espressif/tinyusb/pull/43 dropped one commit: `support format frame based`.
Only `fix uninitialized value` is left.

**Review by tore-espressif — APPROVED** [review]

**Pull request merged**
